export const SUGGESTIONS = [
  "KFC",
  "Hardees",
  "PIZZA HUT",
  "Krispy Kreme",
  "Costa Coffee",
  "Baskin Robbins",
  "Wimpy",
  "TGI Fridays",
  "Chicken Tikka",
  "Peets Coffee",
  "Fish Market",
  "Grand Cafe",
  "Americana",
  "KSA",
  "UAE",
  "Egypt",
  "Kuwait",
  "Qatar",
  "Kazak",
  "Oman",
  "Bahrain",
  "Jordan",
  "Morocco",
  "Iraq",
  "Lebanon",
  "HD",
  "Take Out",
  "Dine In",
  "Drive Thru",
  "Aggregators",
  "Non HD",
  "Americana Assets - App",
  "Call Center",
  "Americana Assets - Web",
  "Contact Center HD",
  "App-Pickup",
  "App-HD",
  "Talabat",
  "Contact Center Pickup",
  "Kiosk",
  "Web-HD",
  "Jahez",
  "ToYou",
  "Web-Pickup",
  "HungerStation",
  "Talabat GO",
  "Deliveroo",
  "Noon",
  "Deliveroo MP",
  "Mrsool",
  "Eat easily",
  "HungerStation FS",
  "Elmenus",
  "Careem Now",
  "Ninja FS",
  "Keeta FS",
  "Careem MP",
  "Glovo",
  "Wolt",
  "Noon FS Cr",
  "Talabat FS",
  "Yandex",
  "Zomato",
  "Chefz",
  "Chocofood",
  "Snoonu",
  "RAFEEQ",
  "Careem NOW",
  "NOON FS",
  "GetCari MP",
  "TMDONE FS",
  "Glovo Credit",
  "Eat Easily MP",
  "INSTA SHOP",
  "Jumia",
  "Cari",
  "RAFEEQ GO",
  "Carriage GO",
  "Snoonu GO",
  "Totters FS",
  "Lezzo",
  "HD Toters",
  "Zomato GO",
  "Instashop FS",
  "Cofe FS",
  "YASSIR",
  "OutSource",
  "Sales",
  "Transactions",
  "Average Check",
  "Budget",
  "Area",
  "Manager",
  "Ops Manager",
  "Country",
  "Store",
  "Restaurant",
  "Market",
  "Brand",
  "Channel",
  "Digital",
  "Home Delivery",
  "Org Week",
  "Month",
  "Week",
  "Year",
  "Date",
  "Trend",
  "Eid Al Adha",
  "Eid Al Fitr",
  "Ramadan",
  "LFL",
  "Same",
  "Pivot",
  "Compare",
  "Contribution",
  "Growth",
  "Top",
  "Bottom",
  "Highest",
  "Lowest",
  "Analyse",
];
